# SPDX-FileCopyrightText: 2022 Empo Inc.
#
# SPDX-License-Identifier: CC0-1.0

name: release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Build binary
        run: msbuild windns.sln -p:Configuration=Release
        working-directory: windns
      - name: artifact prep
        run: mkdir -p ./artifacts
        shell: bash
      - name: Copy artifacts
        run: cp -r windns/bin ./artifacts/windns
        shell: bash
      - name: Artifacts upload
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            artifacts/**
            !artifacts/**/temp/**
